🦈🏠❗ Well I did things - Hopefully nothing breaks ❗🏠🦈

diff --git a/bin/td-toggle b/bin/td-toggle
--- a/bin/td-toggle
+++ b/bin/td-toggle
@@ -1,60 +1,69 @@
 #!/usr/bin/env bash
-
-SCRIPTNAME="$(basename $0)"
-SCRIPTDIR="$(dirname "${BASH_SOURCE[0]}")"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+APPNAME="td-toggle"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : td-toggle
-# @Created     : Wed, Feb 26, 2020, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : If transmission-daemon is running, will ask to kill, else will ask to start.
-#
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-# Set functions
-
-SCRIPTSFUNCTURL="${SCRIPTSAPPFUNCTURL:-https://github.com/dfmgr/installer/raw/master/functions}"
-SCRIPTSFUNCTDIR="${SCRIPTSAPPFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}"
-SCRIPTSFUNCTFILE="${SCRIPTSAPPFUNCTFILE:-applications.bash}"
+#set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-if [ -f "../functions/$SCRIPTSFUNCTFILE" ]; then
-  . "../functions/$SCRIPTSFUNCTFILE"
-elif [ -f "$SCRIPTSFUNCTDIR/functions/$SCRIPTSFUNCTFILE" ]; then
-  . "$SCRIPTSFUNCTDIR/functions/$SCRIPTSFUNCTFILE"
-else
-  curl -LSs "$SCRIPTSFUNCTURL/$SCRIPTSFUNCTFILE" -o "/tmp/$SCRIPTSFUNCTFILE" || exit 1
-  . "/tmp/$SCRIPTSFUNCTFILE"
-fi
-
+##@Version       : 031120212039-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : td-toggle --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 20:39 EST
+# @File          : td-toggle
+# @Description   : If transmission-daemon is running, will ask to kill, else will ask to start.
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-if ! ifinstalled transmission-remote || transmission-remote-cli; then
-  exit 1
-fi
-
-if pgrep -x transmission-da >/dev/null; then
-  if [ "$(printf "No\\nYes" | dmenu -i -p "Kill transmission-daemon?")" = "Yes" ]; then
-    killall transmission-da &&
-      notifications "Torrents" "transmission-daemon killed."
+# helper function
+__help() {
+  printf_help "Usage:  td-toggle |  start/stop transmission daemon"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function
+main() {
+  [ -f "$SRC_DIR/functions.bash" ] && local DIR="$SRC_DIR" || local DIR="$HOME/.local/bin"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    . "$DIR/functions.bash"
   else
-    notifications "Torrents" "User cancelled."
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-else
-  if [ "$(printf "No\\nYes" | dmenu -i -p "Start transmission daemon?")" = "Yes" ]; then
-    transmission-daemon &&
-      notifications "Torrents" "tranmission-daemon started."
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  if [ -f "$(command -v transmission-remote)" ] || [ -f "$(command -v transmission-remote-cli)" ]; then
+  if pgrep -x transmission-da >/dev/null; then
+    if [ "$(printf "No\\nYes" | dmenu -i -p "Kill transmission-daemon?")" = "Yes" ]; then
+      killall transmission-da &&
+        notifications "Torrents" "transmission-daemon killed."
+    else
+      notifications "Torrents" "User cancelled."
+    fi
   else
-    notifications "Torrents" "User cancelled."
+    if [ "$(printf "No\\nYes" | dmenu -i -p "Start transmission daemon?")" = "Yes" ]; then
+      transmission-daemon &&
+        notifications "Torrents" "tranmission-daemon started."
+    else
+      notifications "Torrents" "User cancelled."
+    fi
   fi
-fi
-sleep 3
-
+  sleep 3
+  else
+    return 1
+  fi
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
+# execute function
+main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end
diff --git a/bin/torwrap b/bin/torwrap
--- a/bin/torwrap
+++ b/bin/torwrap
@@ -1,53 +1,65 @@
 #!/usr/bin/env bash
-
-SCRIPTNAME="$(basename $0)"
-SCRIPTDIR="$(dirname "${BASH_SOURCE[0]}")"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+APPNAME="torwrap"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : torwrap
-# @Created     : Wed, Feb 26, 2020, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : open transmission-remote.
-#
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-# Set functions
-
-SCRIPTSFUNCTURL="${SCRIPTSAPPFUNCTURL:-https://github.com/dfmgr/installer/raw/master/functions}"
-SCRIPTSFUNCTDIR="${SCRIPTSAPPFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}"
-SCRIPTSFUNCTFILE="${SCRIPTSAPPFUNCTFILE:-applications.bash}"
+#set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-if [ -f "../functions/$SCRIPTSFUNCTFILE" ]; then
-  . "../functions/$SCRIPTSFUNCTFILE"
-elif [ -f "$SCRIPTSFUNCTDIR/functions/$SCRIPTSFUNCTFILE" ]; then
-  . "$SCRIPTSFUNCTDIR/functions/$SCRIPTSFUNCTFILE"
-else
-  curl -LSs "$SCRIPTSFUNCTURL/$SCRIPTSFUNCTFILE" -o "/tmp/$SCRIPTSFUNCTFILE" || exit 1
-  . "/tmp/$SCRIPTSFUNCTFILE"
-fi
-
+##@Version       : 031120212048-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : torwrap --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 20:48 EST
+# @File          : torwrap
+# @Description   : open transmission-remote.
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-if ! ifinstalled transmission-remote-cli && ! ifinstalled transmission-daemon; then
-  exit 1
-fi
-
-if ! pgrep -x transmission-da >/dev/null; then
-  transmission-daemon
-  notifications "Transmission" "Starting torrent daemon..."
-  sleep 3
-fi
-
-if cmd_exists transmission-remote-cli; then
-  myterminal -e transmission-remote-cli
-fi
-
+# helper function
+__help() {
+  printf_help "Usage:  torwrap |  torwrap "
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
+# Main function
+main() {
+  [ -f "$SRC_DIR/functions.bash" ] && local DIR="$SRC_DIR" || local DIR="$HOME/.local/bin"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    . "$DIR/functions.bash"
+  else
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  if [ -f "$(command -v transmission-remote)" ] || [ -f "$(command -v transmission-remote-cli)" ]; then
+  if ! pgrep -x transmission-da >/dev/null; then
+    transmission-daemon
+    exitCode+=$?
+    notifications "Transmission" "Starting torrent daemon..."
+    sleep 3
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  if [ -f  "$(command -v transmission-remote-cli)" ]; then
+    myterminal -e transmission-remote-cli
+    exitCode+=$?
+  fi
+  else
+    exitCode=1
+  fi
+    return "${exitCode:-$?}"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# execute function
+main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end
diff --git a/bin/trans-notify b/bin/trans-notify
--- a/bin/trans-notify
+++ b/bin/trans-notify
@@ -1,55 +1,61 @@
 #!/usr/bin/env bash
-
-SCRIPTNAME="$(basename $0)"
-SCRIPTDIR="$(dirname "${BASH_SOURCE[0]}")"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+APPNAME="trans-notify"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : trans-notify
-# @Created     : Wed, Feb 26, 2020, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : transmission notification script
-#
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-# Set functions
-
-SCRIPTSFUNCTURL="${SCRIPTSAPPFUNCTURL:-https://github.com/dfmgr/installer/raw/master/functions}"
-SCRIPTSFUNCTDIR="${SCRIPTSAPPFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}"
-SCRIPTSFUNCTFILE="${SCRIPTSAPPFUNCTFILE:-applications.bash}"
+#set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-if [ -f "../functions/$SCRIPTSFUNCTFILE" ]; then
-  . "../functions/$SCRIPTSFUNCTFILE"
-elif [ -f "$SCRIPTSFUNCTDIR/functions/$SCRIPTSFUNCTFILE" ]; then
-  . "$SCRIPTSFUNCTDIR/functions/$SCRIPTSFUNCTFILE"
-else
-  curl -LSs "$SCRIPTSFUNCTURL/$SCRIPTSFUNCTFILE" -o "/tmp/$SCRIPTSFUNCTFILE" || exit 1
-  . "/tmp/$SCRIPTSFUNCTFILE"
-fi
-
+##@Version       : 031120212101-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : trans-notify --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 21:01 EST
+# @File          : trans-notify
+# @Description   : transmission notification script.
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-dldir="$(grep download-dir ~/.config/transmission/settings.json | sed 's#[,"]##g' | awk '{print $2}')"
-
-# Main progam
-
-if cmd_exists notifications; then
+# helper function
+__help() {
+  printf_help "Usage:  trans-notify |  trans-notify "
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function
+main() {
+  [ -f "$SRC_DIR/functions.bash" ] && local DIR="$SRC_DIR" || local DIR="$HOME/.local/bin"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    . "$DIR/functions.bash"
+  else
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  local dldir="$(grep download-dir ~/.config/transmission/settings.json | sed 's#[,"]##g' | awk '{print $2}')"
   notifications "Transmission" "$TR_TORRENT_NAME has been 🔽 to $dldir"
-fi
-
-if [ -n "$PUSHBULLET_ACCESS_TOKEN" ]; then
-  curl -LSsq -u "$PUSHBULLET_ACCESS_TOKEN": \
-    --header 'Content-Type: application/json' \
-    -X POST https://api.pushbullet.com/v2/pushes \
-    -d "{\"type\": \"note\", \"title\": \"Torrent has 🔽 on $HOSTNAME\", \"body\": \"$TR_TORRENT_NAME has been downloaded to $dldir.\"}" \
-    >/dev/null && echo ""
-fi
-
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  if [ -n "$PUSHBULLET_ACCESS_TOKEN" ]; then
+    curl -LSsq -u "$PUSHBULLET_ACCESS_TOKEN": \
+      --header 'Content-Type: application/json' \
+      -X POST https://api.pushbullet.com/v2/pushes \
+      -d "{\"type\": \"note\", \"title\": \"Torrent has 🔽 on $HOSTNAME\", \"body\": \"$TR_TORRENT_NAME has been downloaded to $dldir.\"}" \
+      >/dev/null && echo ""
+  fi
+  return "${exitCode:-$?}"
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
+# execute function
+main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end
+
diff --git a/bin/trans-status b/bin/trans-status
--- a/bin/trans-status
+++ b/bin/trans-status
@@ -1,60 +1,74 @@
 #!/usr/bin/env bash
-
-SCRIPTNAME="$(basename $0)"
-SCRIPTDIR="$(dirname "${BASH_SOURCE[0]}")"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+APPNAME="trans-status"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : trans-status
-# @Created     : Wed, Feb 26, 2020, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : transmission status script
-#
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-# Set functions
-
-SCRIPTSFUNCTURL="${SCRIPTSAPPFUNCTURL:-https://github.com/dfmgr/installer/raw/master/functions}"
-SCRIPTSFUNCTDIR="${SCRIPTSAPPFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}"
-SCRIPTSFUNCTFILE="${SCRIPTSAPPFUNCTFILE:-applications.bash}"
+#set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-if [ -f "../functions/$SCRIPTSFUNCTFILE" ]; then
-  . "../functions/$SCRIPTSFUNCTFILE"
-elif [ -f "$SCRIPTSFUNCTDIR/functions/$SCRIPTSFUNCTFILE" ]; then
-  . "$SCRIPTSFUNCTDIR/functions/$SCRIPTSFUNCTFILE"
-else
-  curl -LSs "$SCRIPTSFUNCTURL/$SCRIPTSFUNCTFILE" -o "/tmp/$SCRIPTSFUNCTFILE" || exit 1
-  . "/tmp/$SCRIPTSFUNCTFILE"
-fi
-
+##@Version       : 031120212105-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : trans-status --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 21:05 EST
+# @File          : trans-status
+# @Description   : transmission status script.
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-BLOCK="${BLOCK_BUTTON:-$1}"
-
-status() {
-  transmission-remote -l | grep % |
-    sed " # This first sed command is to ensure a desirable order with sort
-  s/.*Stopped.*/A/g;
-  s/.*Seeding.*/Z/g;
-  s/.*100%.*/N/g;
-  s/.*Idle.*/B/g;
-  s/.*Uploading.*/L/g;
-  s/.*%.*/M/g" |
-    sort -h | uniq -c | sed " # Now we replace the standin letters with icons.
+# helper function
+__help() {
+  printf_help "Usage:  trans-status |  trans-status "
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function
+main() {
+  [ -f "$SRC_DIR/functions.bash" ] && local DIR="$SRC_DIR" || local DIR="$HOME/.local/bin"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    . "$DIR/functions.bash"
+  else
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
+  fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  local BLOCK="${BLOCK_BUTTON:-$1}"
+  local SERVER="${TORRENT_SERVER:-localhost}:9091"
+  status() {
+    transmission-remote "$SERVER" -l | grep % |
+      sed " # This first sed command is to ensure a desirable order with sort
+      s/.*Stopped.*/A/g;
+      s/.*Seeding.*/Z/g;
+      s/.*100%.*/N/g;
+      s/.*Idle.*/B/g;
+      s/.*Uploading.*/L/g;
+      s/.*%.*/M/g" |
+      sort -h | uniq -c | sed " # Now we replace the standin letters with icons.
         s/A/🛑/g;
         s/B/⌛️/g;
         s/L/🔼/g;
         s/M/🔽/g;
         s/N/✅/g;
         s/Z/🌱/g" | awk '{print $2, $1}' | sed -e "s/ $//g" | tr '\n' ' '
+    }
+  case $BLOCK in
+    1) myterminal -e mytorrent 2>/dev/null && exitCode=0 || exitCode=1;;
+    *) status 2>/dev/null && exitCode=0 || exitCode=1; echo ;;
+  esac
+  return ${exitCode:-$?}
 }
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# execute function
+main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# end
 
-case $BLOCK in
-1) myterminal -e transmission-remote-cli 2>/dev/null ;;
-*) status && echo ;;
-esac
diff --git a/bin/transadd b/bin/transadd
--- a/bin/transadd
+++ b/bin/transadd
@@ -1,73 +1,93 @@
 #!/usr/bin/env bash
-
-SCRIPTNAME="$(basename $0)"
-SCRIPTDIR="$(dirname "${BASH_SOURCE[0]}")"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+APPNAME="transadd"
 USER="${SUDO_USER:-${USER}}"
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : td-toggle
-# @Created     : Wed, Feb 26, 2020, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : Mimeapp script for adding torrent to transmission-daemon
-#
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-# Set functions
-
-SCRIPTSFUNCTURL="${SCRIPTSAPPFUNCTURL:-https://github.com/dfmgr/installer/raw/master/functions}"
-SCRIPTSFUNCTDIR="${SCRIPTSAPPFUNCTDIR:-/usr/local/share/CasjaysDev/scripts}"
-SCRIPTSFUNCTFILE="${SCRIPTSAPPFUNCTFILE:-applications.bash}"
+#set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-if [ -f "../functions/$SCRIPTSFUNCTFILE" ]; then
-  . "../functions/$SCRIPTSFUNCTFILE"
-elif [ -f "$SCRIPTSFUNCTDIR/functions/$SCRIPTSFUNCTFILE" ]; then
-  . "$SCRIPTSFUNCTDIR/functions/$SCRIPTSFUNCTFILE"
-else
-  curl -LSs "$SCRIPTSFUNCTURL/$SCRIPTSFUNCTFILE" -o "/tmp/$SCRIPTSFUNCTFILE" || exit 1
-  . "/tmp/$SCRIPTSFUNCTFILE"
-fi
-
+##@Version       : 031120212054-git
+# @Author        : Jason Hempstead
+# @Contact       : jason@casjaysdev.com
+# @License       : WTFPL
+# @ReadME        : transadd --help
+# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
+# @Created       : Thursday, Mar 11, 2021 20:54 EST
+# @File          : transadd
+# @Description   : Mimeapp script for adding torrent to transmission-daemon.
+# @TODO          :
+# @Other         :
+# @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-if [ "$1" = "" ]; then
-  notifications "Transmission" "Error: No torrent file recieved"
-  exit 1
-fi
-
-if cmd_exists transmission-daemon; then
-  if ! pgrep -x transmission-da >/dev/null >&1; then
-    transmission-daemon &
-    notifications "Transmission" "Starting transmission daemon..."
-    sleep 3
-  fi
-  transmission-remote -a "$@"
-  RETV="$?" && sleep 10
-  if [ "$RETV" -eq 0 ]; then
-    notifications "Transmission" "🔽 Torrent added."
+# helper function
+__help() {
+  printf_help "Usage:  transadd torrent  |  transadd path/to/torrent/file"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function
+main() {
+  [ -f "$SRC_DIR/functions.bash" ] && local DIR="$SRC_DIR" || local DIR="$HOME/.local/bin"
+  if [[ -f "$DIR/functions.bash" ]]; then
+    . "$DIR/functions.bash"
   else
-    notifications "Transmission" "🔽 Torrent failed."
+    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
+    return 1
   fi
-elif cmd_exists transmission-gtk; then
-  if ! pgrep -x transmission-gt >/dev/null >&1; then
-    transmission-gtk &
-    notifications "Transmission" "Starting transmission gui..."
-    sleep 3
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  [ "$1" = "--help" ] && __help
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  if [ "$1" = "" ]; then
+    notifications "Transmission" "Error: No torrent file recieved"
+    exit 1
   fi
-  transmission-gtk "$@"
-  RETV="$?" && sleep 10
-  if [ "$RETV" -eq 0 ]; then
-    notifications "Transmission" "🔽 Torrent added."
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  if [ -f "$(command -v transmission-daemon 2>/dev/null)" ]; then
+    if ! pgrep -x transmission-da &>/dev/null; then
+      transmission-daemon &
+        notifications "Transmission" "Starting transmission daemon..."
+      sleep 3
+    fi
+    transmission-remote -a "$@" &>/dev/null
+    exitCode="$?" && sleep 10
+    if [ "$exitCode" -eq 0 ]; then
+      notifications "Transmission" "🔽 Torrent added."
+    else
+      notifications "Transmission" "🔽 Torrent failed."
+    fi
+  elif [ -f "$(command -v transmission-remote-gtk 2>/dev/null)" ]; then
+    if ! pgrep -x transmission-re &>/dev/null; then
+      transmission-remote-gtk &>/dev/null &
+      notifications "Transmission" "Starting transmission gui..."
+      sleep 3
+    fi
+    transmission-remote-gtk "$@" 2>/dev/null
+    exitCode="$?" && sleep 10
+  elif [ -f "$(command -v transmission-gtk 2>/dev/null)" ]; then
+    if ! pgrep -x transmission-gt &>/dev/null; then
+      transmission-gtk &
+      notifications "Transmission" "Starting transmission gui..."
+      sleep 3
+    fi
+    transmission-gtk "$@" &>/dev/null
+    exitCode="$?" && sleep 10
+    if [ "$exitCode" -eq 0 ]; then
+      notifications "Transmission" "🔽 Torrent added."
+    else
+      notifications "Transmission" "🔽 Torrent failed."
+    fi
   else
-    notifications "Transmission" "🔽 Torrent failed."
+    exitCode=1
   fi
-
-fi
-
+    return "${exitCode:-$?}"
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
+# execute function
+main "$@"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+exit $?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end
+
