🦈🏠❗ Well I did things - Hopefully nothing breaks ❗🏠🦈

diff --git a/bin/td-toggle b/bin/td-toggle
--- a/bin/td-toggle
+++ b/bin/td-toggle
@@ -1,65 +1,87 @@
 #!/usr/bin/env bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-APPNAME="td-toggle"
+PROG="td-toggle"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
 SRC_DIR="${BASH_SOURCE%/*}"
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 #set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 031120212039-git
+##@Version       : 031520212024-git
 # @Author        : Jason Hempstead
 # @Contact       : jason@casjaysdev.com
 # @License       : WTFPL
 # @ReadME        : td-toggle --help
 # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Thursday, Mar 11, 2021 20:39 EST
+# @Created       : Monday, Mar 15, 2021 20:24 EDT
 # @File          : td-toggle
 # @Description   : If transmission-daemon is running, will ask to kill, else will ask to start.
 # @TODO          :
 # @Other         :
 # @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function file
+if [ -f "$SRC_DIR/functions.bash" ]; then
+  FUNCTIONS_DIR="$SRC_DIR"
+  . "$FUNCTIONS_DIR/functions.bash"
+elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+  FUNCTIONS_DIR="$HOME/.local/bin"
+  . "$FUNCTIONS_DIR/functions.bash"
+else
+  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+  return 1
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # helper function
+__version() { app_version; }
 __help() {
-  printf_help "Usage:  td-toggle |  start/stop transmission daemon"
+  app_help "Usage: td-toggle  -  td-toggle --version"  \
+    "-v, --version          -  display version" \
+    "-h, --help             -  display help"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
 main() {
-  [ -f "$SRC_DIR/functions.bash" ] && local DIR="$SRC_DIR" || local DIR="$HOME/.local/bin"
-  if [[ -f "$DIR/functions.bash" ]]; then
-    . "$DIR/functions.bash"
-  else
-    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
-    return 1
-  fi
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  [ "$1" = "--help" ] && __help
+  # options
+  case $1 in
+    -v | --version) __version ;;
+    -h | --help) __help ;;
+  esac
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Required app check
+  cmd_exists --error bash || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  export SEND_NOTIFY=no
+  # begin main app
   local SERVER="${TORRENT_SERVER:-localhost}:9091"
   if [ -f "$(command -v transmission-remote)" ] || [ -f "$(command -v transmission-remote-cli)" ]; then
     if pgrep -x transmission-da >/dev/null; then
-      if [ "$(printf "No\\nYes" | dmenu -i -p "Kill transmission-daemon?")" = "Yes" ]; then
+      if ask_confirm "Kill transmission-daemon?"; then
         killall transmission-da &&
           notifications "Torrents" "transmission-daemon killed."
       else
         notifications "Torrents" "User cancelled."
       fi
     else
-      if [ "$(printf "No\\nYes" | dmenu -i -p "Start transmission daemon?")" = "Yes" ]; then
-        transmission-daemon "$SERVER" &&
+      if ask_confirm "Start transmission daemon?"; then
+        transmission-daemon &&
           notifications "Torrents" "tranmission-daemon started."
       else
         notifications "Torrents" "User cancelled."
+        exitCode=1
       fi
     fi
     sleep 3
   else
-    return 1
+    if eval mytorrents; then
+      exitCode=0
+    else
+      exitCode=1
+    fi
   fi
+  return "${exitCode:-$?}"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # execute function
@@ -68,3 +90,4 @@ main "$@"
 exit $?
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end
+
diff --git a/bin/torwrap b/bin/torwrap
--- a/bin/torwrap
+++ b/bin/torwrap
@@ -1,44 +1,59 @@
 #!/usr/bin/env bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-APPNAME="torwrap"
+PROG="torwrap"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
 SRC_DIR="${BASH_SOURCE%/*}"
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 #set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 031120212048-git
+##@Version       : 031620210541-git
 # @Author        : Jason Hempstead
 # @Contact       : jason@casjaysdev.com
 # @License       : WTFPL
 # @ReadME        : torwrap --help
 # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Thursday, Mar 11, 2021 20:48 EST
+# @Created       : Tuesday, Mar 16, 2021 05:41 EDT
 # @File          : torwrap
 # @Description   : open transmission-remote.
 # @TODO          :
 # @Other         :
 # @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function file
+if [ -f "$SRC_DIR/functions.bash" ]; then
+  FUNCTIONS_DIR="$SRC_DIR"
+  . "$FUNCTIONS_DIR/functions.bash"
+elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+  FUNCTIONS_DIR="$HOME/.local/bin"
+  . "$FUNCTIONS_DIR/functions.bash"
+else
+  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+  return 1
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # helper function
+__version() { app_version; }
 __help() {
-  printf_help "Usage:  torwrap |  torwrap "
+  app_help "Usage: torwrap  -  torwrap --version"  \
+    "-v, --version          -  display version" \
+    "-h, --help             -  display help"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
 main() {
-  [ -f "$SRC_DIR/functions.bash" ] && local DIR="$SRC_DIR" || local DIR="$HOME/.local/bin"
-  if [[ -f "$DIR/functions.bash" ]]; then
-    . "$DIR/functions.bash"
-  else
-    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
-    return 1
-  fi
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  [ "$1" = "--help" ] && __help
+  # options
+  case $1 in
+    -v | --version) __version ;;
+    -h | --help) __help ;;
+  esac
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Required app check
+  cmd_exists --error bash || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
   if [ -f "$(command -v transmission-remote)" ] || [ -f "$(command -v transmission-remote-cli)" ]; then
     if ! pgrep -x transmission-da >/dev/null; then
       transmission-daemon
@@ -47,7 +62,10 @@ main() {
       sleep 3
     fi
     # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-    if [ -f "$(command -v transmission-remote-cli)" ]; then
+    if [ -n "$TORRENT" ]; then
+      eval $TORRENT
+      exitCode=$?
+    elif [ -f "$(command -v transmission-remote-cli)" ]; then
       myterminal -e transmission-remote-cli
       exitCode+=$?
     fi
@@ -63,3 +81,4 @@ main "$@"
 exit $?
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end
+
diff --git a/bin/trans-notify b/bin/trans-notify
--- a/bin/trans-notify
+++ b/bin/trans-notify
@@ -1,56 +1,74 @@
 #!/usr/bin/env bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-APPNAME="trans-notify"
+PROG="trans-notify"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
 SRC_DIR="${BASH_SOURCE%/*}"
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 #set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 031120212101-git
+##@Version       : 031620210728-git
 # @Author        : Jason Hempstead
 # @Contact       : jason@casjaysdev.com
 # @License       : WTFPL
 # @ReadME        : trans-notify --help
 # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Thursday, Mar 11, 2021 21:01 EST
+# @Created       : Tuesday, Mar 16, 2021 07:28 EDT
 # @File          : trans-notify
 # @Description   : transmission notification script.
 # @TODO          :
 # @Other         :
 # @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function file
+if [ -f "$SRC_DIR/functions.bash" ]; then
+  FUNCTIONS_DIR="$SRC_DIR"
+  . "$FUNCTIONS_DIR/functions.bash"
+elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+  FUNCTIONS_DIR="$HOME/.local/bin"
+  . "$FUNCTIONS_DIR/functions.bash"
+else
+  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+  return 1
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # helper function
+__version() { app_version; }
 __help() {
-  printf_help "Usage:  trans-notify |  trans-notify "
+  app_help "Usage: trans-notify  -  trans-notify --version"  \
+    "-v, --version          -  display version" \
+    "-h, --help             -  display help"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
 main() {
-  [ -f "$SRC_DIR/functions.bash" ] && local DIR="$SRC_DIR" || local DIR="$HOME/.local/bin"
-  if [[ -f "$DIR/functions.bash" ]]; then
-    . "$DIR/functions.bash"
-  else
-    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
-    return 1
-  fi
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  [ "$1" = "--help" ] && __help
+  # options
+  case $1 in
+    -v | --version) __version ;;
+    -h | --help) __help ;;
+  esac
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  if [ -"$HOME/.config/transmission/settings.json" ]; then
+  # Required app check
+  cmd_exists --error bash || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
+  local NAME="${TR_TORRENT_NAME:-A torrent}"
+  if [ -"$HOME/.config/transmission/settings.json1" ]; then
     local dldir="$(grep download-dir "$HOME/.config/transmission/settings.json" | sed 's#[,"]##g' | awk '{print $2}')"
-    notifications "Transmission" "$TR_TORRENT_NAME has been 🔽 to $dldir"
+    notifications "Transmission" "$NAME has been 🔽 to $dldir"
     # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+    if am_i_online; then
     if [ -n "$PUSHBULLET_ACCESS_TOKEN" ]; then
-      curl -LSsq -u "$PUSHBULLET_ACCESS_TOKEN": \
+      curl -q -LSs -u "$PUSHBULLET_ACCESS_TOKEN": \
         --header 'Content-Type: application/json' \
         -X POST https://api.pushbullet.com/v2/pushes \
-        -d "{\"type\": \"note\", \"title\": \"Torrent has 🔽 on $HOSTNAME\", \"body\": \"$TR_TORRENT_NAME has been downloaded to $dldir.\"}" \
-        >/dev/null && echo ""
+        -d "{\"type\": \"note\", \"title\": \"Torrent has 🔽 on $HOSTNAME\", \"body\": \"$NAME has been downloaded to $dldir.\"}">/dev/null && echo ""
+    fi
     fi
   else
+    notifications "Transmission" "Is transmission installed?"
     exitCode=1
   fi
   return "${exitCode:-$?}"
@@ -62,3 +80,4 @@ main "$@"
 exit $?
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end
+
diff --git a/bin/trans-status b/bin/trans-status
--- a/bin/trans-status
+++ b/bin/trans-status
@@ -1,46 +1,61 @@
 #!/usr/bin/env bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-APPNAME="trans-status"
+PROG="trans-status"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
 SRC_DIR="${BASH_SOURCE%/*}"
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 #set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 031120212105-git
+##@Version       : 031620210739-git
 # @Author        : Jason Hempstead
 # @Contact       : jason@casjaysdev.com
 # @License       : WTFPL
 # @ReadME        : trans-status --help
 # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Thursday, Mar 11, 2021 21:05 EST
+# @Created       : Tuesday, Mar 16, 2021 07:39 EDT
 # @File          : trans-status
 # @Description   : transmission status script.
 # @TODO          :
 # @Other         :
 # @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function file
+if [ -f "$SRC_DIR/functions.bash" ]; then
+  FUNCTIONS_DIR="$SRC_DIR"
+  . "$FUNCTIONS_DIR/functions.bash"
+elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+  FUNCTIONS_DIR="$HOME/.local/bin"
+  . "$FUNCTIONS_DIR/functions.bash"
+else
+  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+  return 1
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # helper function
+__version() { app_version; }
 __help() {
-  printf_help "Usage:  trans-status |  Show transmission status "
+  printf_help "Usage:  trans-status |  Show transmission status "  \
+    "-v, --version          -  display version" \
+    "-h, --help             -  display help"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
 main() {
-  [ -f "$SRC_DIR/functions.bash" ] && local DIR="$SRC_DIR" || local DIR="$HOME/.local/bin"
-  if [[ -f "$DIR/functions.bash" ]]; then
-    . "$DIR/functions.bash"
-  else
-    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
-    return 1
-  fi
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  [ "$1" = "--help" ] && __help
+  # options
+  case $1 in
+    -v | --version) __version ;;
+    -h | --help) __help ;;
+  esac
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Required app check
+  cmd_exists --error bash || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
   local BLOCK="${BLOCK_BUTTON:-$1}"
-  local SERVER="${TORRENT_SERVER:-localhost}:9091"
+  local SERVER="${TORRENT_SERVER:-localhost:9091}"
   status() {
     transmission-remote "$SERVER" -l | grep % |
       sed " # This first sed command is to ensure a desirable order with sort
@@ -74,3 +89,4 @@ main "$@"
 exit $?
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end
+
diff --git a/bin/transadd b/bin/transadd
--- a/bin/transadd
+++ b/bin/transadd
@@ -1,48 +1,65 @@
 #!/usr/bin/env bash
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-APPNAME="transadd"
+PROG="transadd"
 USER="${SUDO_USER:-${USER}}"
 HOME="${USER_HOME:-${HOME}}"
 SRC_DIR="${BASH_SOURCE%/*}"
-
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 #set opts
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-##@Version       : 031120212054-git
+##@Version       : 031620210558-git
 # @Author        : Jason Hempstead
 # @Contact       : jason@casjaysdev.com
 # @License       : WTFPL
 # @ReadME        : transadd --help
 # @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
-# @Created       : Thursday, Mar 11, 2021 20:54 EST
+# @Created       : Tuesday, Mar 16, 2021 05:58 EDT
 # @File          : transadd
 # @Description   : Mimeapp script for adding torrent to transmission-daemon.
 # @TODO          :
 # @Other         :
 # @Resource      :
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Main function file
+if [ -f "$SRC_DIR/functions.bash" ]; then
+  FUNCTIONS_DIR="$SRC_DIR"
+  . "$FUNCTIONS_DIR/functions.bash"
+elif [ -f "$HOME/.local/bin/functions.bash" ]; then
+  FUNCTIONS_DIR="$HOME/.local/bin"
+  . "$FUNCTIONS_DIR/functions.bash"
+else
+  printf "\t\t\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $FUNCTIONS_DIR"
+  return 1
+fi
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # helper function
+__version() { app_version; }
 __help() {
-  printf_help "Usage:  transadd torrent  |  transadd path/to/torrent/file"
+  app_help "Usage: transadd  -  transadd --version"  \
+    "-v, --version          -  display version" \
+    "-h, --help             -  display help"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main function
 main() {
-  if [ -f "$SRC_DIR/functions.bash" ]; then local DIR="$SRC_DIR"; else local DIR="$HOME/.local/bin"; fi
-  if [[ -f "$DIR/functions.bash" ]]; then
-    . "$DIR/functions.bash"
-  else
-    printf "\t\t\\033[0;31m%s \033[0m\n" "Couldn't source the functions file from $DIR"
-    return 1
-  fi
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-  [ "$1" = "--help" ] && __help
+  # options
+  case $1 in
+    -v | --version) __version ;;
+    -h | --help) __help ;;
+  esac
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # Required app check
+  cmd_exists --error bash || exit 1
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  # begin main app
   if [ "$1" = "" ]; then
     notifications "Transmission" "Error: No torrent file recieved"
     exit 1
   fi
+  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+  #check_local "$1" || check_uri "$1" || notifications "Transmission" "Error: unknown torrent location"
   # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   local SERVER="${TORRENT_SERVER:-localhost}:9091"
   if [ -f "$(command -v transmission-daemon 2>/dev/null)" ]; then
@@ -91,3 +108,4 @@ main "$@"
 exit $?
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # end
+
